// ─── CATEGORIES ────────────────────────────────────────────────────────────────
export const CATEGORIES = [
  { id: 'all',      label: 'All Tools',    emoji: '🗂️' },
  { id: 'organize', label: 'Organize PDF', emoji: '📂' },
  { id: 'optimize', label: 'Optimize PDF', emoji: '⚡' },
  { id: 'convert',  label: 'Convert PDF',  emoji: '🔄' },
  { id: 'edit',     label: 'Edit PDF',     emoji: '✏️' },
  { id: 'secure',   label: 'Secure PDF',   emoji: '🔐' },
  { id: 'ai',       label: 'AI Tools',     emoji: '🤖' },
]

// ─── TOOLS ─────────────────────────────────────────────────────────────────────
export const TOOLS = [
  // ── ORGANIZE ──────────────────────────────────────────────────────────────
  {
    id: 'merge-pdf',
    name: 'Merge PDF',
    description: 'Combine multiple PDFs into one file in the order you choose.',
    icon: '🔗',
    color: 'from-orange-400 to-red-500',
    accepts: '.pdf',
    category: 'organize',
    status: 'live',
  },
  {
    id: 'split-pdf',
    name: 'Split PDF',
    description: 'Separate a PDF into individual pages or ranges.',
    icon: '✂️',
    color: 'from-red-400 to-rose-600',
    accepts: '.pdf',
    category: 'organize',
    status: 'live',
  },
  {
    id: 'reorder-pages',
    name: 'Reorder Pages',
    description: 'Change the order of PDF pages in any sequence.',
    icon: '↕️',
    color: 'from-indigo-400 to-purple-600',
    accepts: '.pdf',
    category: 'organize',
    status: 'live',
  },
  {
    id: 'extract-pages',
    name: 'Extract Pages',
    description: 'Pull out specific pages from a PDF into a new file.',
    icon: '📋',
    color: 'from-pink-400 to-rose-600',
    accepts: '.pdf',
    category: 'organize',
    status: 'live',
  },
  {
    id: 'scan-to-pdf',
    name: 'Scan to PDF',
    description: 'Use your camera to scan documents directly to PDF.',
    icon: '📷',
    color: 'from-teal-400 to-cyan-600',
    accepts: null,
    category: 'organize',
    status: 'live',
  },

  // ── OPTIMIZE ──────────────────────────────────────────────────────────────
  {
    id: 'compress-pdf',
    name: 'Compress PDF',
    description: 'Reduce PDF file size while keeping it readable.',
    icon: '🗜️',
    color: 'from-yellow-400 to-orange-500',
    accepts: '.pdf',
    category: 'optimize',
    status: 'live',
  },
  {
    id: 'repair-pdf',
    name: 'Repair PDF',
    description: 'Fix corrupted or damaged PDF files automatically.',
    icon: '🔧',
    color: 'from-green-400 to-emerald-600',
    accepts: '.pdf',
    category: 'optimize',
    status: 'live',
  },
  {
    id: 'ocr-pdf',
    name: 'OCR PDF',
    description: 'Extract text from scanned images using OCR. Convert PDF to JPG first.',
    icon: '🔍',
    color: 'from-lime-400 to-green-600',
    accepts: '.jpg,.jpeg,.png,.webp',
    category: 'optimize',
    status: 'live',
  },

  // ── CONVERT ───────────────────────────────────────────────────────────────
  {
    id: 'pdf-to-jpg',
    name: 'PDF to JPG',
    description: 'Convert each PDF page to a high-quality JPG image.',
    icon: '🖼️',
    color: 'from-orange-400 to-amber-500',
    accepts: '.pdf',
    category: 'convert',
    status: 'live',
  },
  {
    id: 'jpg-to-pdf',
    name: 'JPG to PDF',
    description: 'Turn JPG, PNG, or WebP images into a PDF document.',
    icon: '📄',
    color: 'from-green-400 to-emerald-600',
    accepts: '.jpg,.jpeg,.png,.webp',
    category: 'convert',
    status: 'live',
  },
  {
    id: 'word-to-pdf',
    name: 'Word to PDF',
    description: 'Convert .doc and .docx Word files to PDF.',
    icon: '📝',
    color: 'from-blue-500 to-blue-700',
    accepts: '.doc,.docx',
    category: 'convert',
    status: 'live',
  },
  {
    id: 'pdf-to-word',
    name: 'PDF to Word',
    description: 'Convert PDF files into editable Word documents.',
    icon: '✏️',
    color: 'from-sky-400 to-blue-600',
    accepts: '.pdf',
    category: 'convert',
    status: 'live',
  },
  {
    id: 'excel-to-pdf',
    name: 'Excel to PDF',
    description: 'Convert Excel spreadsheets to PDF format.',
    icon: '📊',
    color: 'from-green-500 to-green-700',
    accepts: '.xls,.xlsx',
    category: 'convert',
    status: 'live',
  },
  {
    id: 'pdf-to-excel',
    name: 'PDF to Excel',
    description: 'Extract tables from a PDF into an Excel spreadsheet.',
    icon: '📈',
    color: 'from-emerald-400 to-green-600',
    accepts: '.pdf',
    category: 'convert',
    status: 'live',
  },
  {
    id: 'pptx-to-pdf',
    name: 'PPT to PDF',
    description: 'Convert PowerPoint presentations to PDF slides.',
    icon: '📑',
    color: 'from-red-400 to-orange-600',
    accepts: '.ppt,.pptx',
    category: 'convert',
    status: 'live',
  },
  {
    id: 'html-to-pdf',
    name: 'HTML to PDF',
    description: 'Convert HTML code, uploaded HTML files, or webpages into PDF documents.',
    icon: '🌐',
    color: 'from-violet-400 to-purple-600',
    accepts: null,
    category: 'convert',
    status: 'live',
  },
  {
    id: 'pdf-to-pptx',
    name: 'PDF to PPT',
    description: 'Turn PDF pages into PowerPoint presentation slides.',
    icon: '🎞️',
    color: 'from-orange-500 to-red-600',
    accepts: '.pdf',
    category: 'convert',
    status: 'live',
  },

  // ── EDIT ──────────────────────────────────────────────────────────────────
  {
    id: 'rotate-pdf',
    name: 'Rotate PDF',
    description: 'Rotate PDF pages 90°, 180°, or 270° in one click.',
    icon: '🔄',
    color: 'from-teal-400 to-cyan-600',
    accepts: '.pdf',
    category: 'edit',
    status: 'live',
  },
  {
    id: 'pdf-watermark',
    name: 'Watermark PDF',
    description: 'Stamp custom text or diagonal watermarks on every page.',
    icon: '💧',
    color: 'from-cyan-400 to-blue-600',
    accepts: '.pdf',
    category: 'edit',
    status: 'live',
  },
  {
    id: 'page-numbers',
    name: 'Page Numbers',
    description: 'Add page numbers to PDFs — choose position and style.',
    icon: '🔢',
    color: 'from-purple-400 to-violet-600',
    accepts: '.pdf',
    category: 'edit',
    status: 'live',
  },
  {
    id: 'crop-pdf',
    name: 'Crop PDF',
    description: 'Crop margins of PDF pages to remove whitespace or unwanted areas.',
    icon: '✂️',
    color: 'from-pink-500 to-rose-600',
    accepts: '.pdf',
    category: 'edit',
    status: 'live',
  },
  {
    id: 'redact-pdf',
    name: 'Redact PDF',
    description: 'Permanently black out sensitive text and graphics from PDFs.',
    icon: '🖤',
    color: 'from-gray-600 to-gray-800',
    accepts: '.pdf',
    category: 'edit',
    status: 'live',
  },
  {
    id: 'edit-pdf',
    name: 'Edit PDF',
    description: 'Add text, shapes, images, and freehand annotations to any PDF.',
    icon: '🖊️',
    color: 'from-violet-500 to-purple-700',
    accepts: '.pdf',
    category: 'edit',
    status: 'coming-soon',
  },
  {
    id: 'pdf-forms',
    name: 'PDF Forms',
    description: 'Detect form fields and create interactive fillable PDFs.',
    icon: '📋',
    color: 'from-blue-400 to-indigo-600',
    accepts: '.pdf',
    category: 'edit',
    status: 'coming-soon',
  },

  // ── SECURE ────────────────────────────────────────────────────────────────
  {
    id: 'protect-pdf',
    name: 'Protect PDF',
    description: 'Encrypt your PDF with a password to prevent unauthorized access.',
    icon: '🔒',
    color: 'from-blue-600 to-indigo-700',
    accepts: '.pdf',
    category: 'secure',
    status: 'live',
  },
  {
    id: 'unlock-pdf',
    name: 'Unlock PDF',
    description: 'Remove password protection from PDFs you own.',
    icon: '🔓',
    color: 'from-amber-400 to-orange-500',
    accepts: '.pdf',
    category: 'secure',
    status: 'live',
  },
  {
    id: 'sign-pdf',
    name: 'Sign PDF',
    description: 'Draw or type your signature and embed it into any PDF.',
    icon: '✍️',
    color: 'from-indigo-400 to-blue-600',
    accepts: '.pdf',
    category: 'secure',
    status: 'live',
  },
  {
    id: 'compare-pdf',
    name: 'Compare PDF',
    description: 'Side-by-side comparison of two PDFs to spot differences.',
    icon: '⚖️',
    color: 'from-teal-500 to-cyan-700',
    accepts: '.pdf',
    category: 'secure',
    status: 'coming-soon',
  },

  // ── AI TOOLS ──────────────────────────────────────────────────────────────
  {
    id: 'ai-summarizer',
    name: 'AI Summarizer',
    description: 'Get a smart AI-generated summary of any PDF in seconds.',
    icon: '🤖',
    color: 'from-violet-500 to-fuchsia-600',
    accepts: '.pdf',
    category: 'ai',
    status: 'coming-soon',
  },
  {
    id: 'translate-pdf',
    name: 'Translate PDF',
    description: 'Translate your PDF into Hindi, English, or 10+ other languages.',
    icon: '🌏',
    color: 'from-fuchsia-400 to-pink-600',
    accepts: '.pdf',
    category: 'ai',
    status: 'coming-soon',
  },
]

// ─── MISC ──────────────────────────────────────────────────────────────────────

// 7 Indian languages
export const INDIAN_LANGUAGES = [
  { code: 'en',  label: 'English',  native: 'English'    },
  { code: 'hi',  label: 'Hindi',    native: 'हिन्दी'      },
  { code: 'ta',  label: 'Tamil',    native: 'தமிழ்'       },
  { code: 'te',  label: 'Telugu',   native: 'తెలుగు'      },
  { code: 'bn',  label: 'Bengali',  native: 'বাংলা'       },
  { code: 'mr',  label: 'Marathi',  native: 'मराठी'       },
  { code: 'gu',  label: 'Gujarati', native: 'ગુજરાતી'     },
]

// 24 International languages (from screenshot)
export const INTERNATIONAL_LANGUAGES = [
  { code: 'es',    label: 'Spanish',            native: 'Español'          },
  { code: 'fr',    label: 'French',             native: 'Français'         },
  { code: 'de',    label: 'German',             native: 'Deutsch'          },
  { code: 'it',    label: 'Italian',            native: 'Italiano'         },
  { code: 'pt',    label: 'Portuguese',         native: 'Português'        },
  { code: 'ja',    label: 'Japanese',           native: '日本語'            },
  { code: 'ru',    label: 'Russian',            native: 'Русский'          },
  { code: 'ko',    label: 'Korean',             native: '한국어'             },
  { code: 'zh-cn', label: 'Chinese Simplified', native: '中文 (简体)'       },
  { code: 'zh-tw', label: 'Chinese Traditional',native: '中文 (繁體)'       },
  { code: 'ar',    label: 'Arabic',             native: 'العربية'          },
  { code: 'nl',    label: 'Dutch',              native: 'Nederlands'       },
  { code: 'el',    label: 'Greek',              native: 'Ελληνικά'         },
  { code: 'id',    label: 'Indonesian',         native: 'Bahasa Indonesia' },
  { code: 'ms',    label: 'Malay',              native: 'Bahasa Melayu'    },
  { code: 'pl',    label: 'Polish',             native: 'Polski'           },
  { code: 'sv',    label: 'Swedish',            native: 'Svenska'          },
  { code: 'th',    label: 'Thai',               native: 'ภาษาไทย'          },
  { code: 'tr',    label: 'Turkish',            native: 'Türkçe'           },
  { code: 'uk',    label: 'Ukrainian',          native: 'Українська'       },
  { code: 'vi',    label: 'Vietnamese',         native: 'Tiếng Việt'       },
  { code: 'sw',    label: 'Kiswahili',          native: 'Kiswahili'        },
]

// All languages combined
export const LANGUAGES = [...INDIAN_LANGUAGES, ...INTERNATIONAL_LANGUAGES]

export const MAX_FILE_SIZE_MB    = Infinity
export const MAX_FILE_SIZE_BYTES = Number.MAX_SAFE_INTEGER
